apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-api
  template:
    metadata:
      labels:
        app: healthcare-api
    spec:
      containers:
      - name: api
        image: healthcare-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: JWT_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: ENCRYPTION_KEY
        - name: SUPER_ADMIN_SETUP_KEY
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: SUPER_ADMIN_SETUP_KEY
        - name: ALLOW_ORIGINS
          value: "https://yourdomain.com,http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-api-service
spec:
  selector:
    app: healthcare-api
  ports:
  - port: 80
    targetPort: 8000
    type: LoadBalancer
