apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-api
  template:
    metadata:
      labels:
        app: healthcare-api
    spec:
      containers:
      - name: api
        image: healthcare-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/healthcare"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-api-service
spec:
  selector:
    app: healthcare-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer