version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app: # Your Python backend service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rural-health-backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: python3 main.py

volumes:
  postgres_data: